/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update profile settings
         * @description Changing `timezone` or `all_day_reminder_time` recomputes pending reminders.
         */
        patch: operations["patchMe"];
        trace?: never;
    };
    "/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All lists the caller is a member of */
        get: operations["listLists"];
        put?: never;
        /** Create a list (idempotent on `id`) */
        post: operations["createList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getList"];
        put?: never;
        post?: never;
        /** @description Soft-deletes the list and its tasks. The inbox list cannot be deleted (409). */
        delete: operations["deleteList"];
        options?: never;
        head?: never;
        /** @description The inbox list cannot be renamed (409). */
        patch: operations["patchList"];
        trace?: never;
    };
    "/lists/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Restores the list and the tasks deleted together with it. 409 after the restore window. */
        post: operations["restoreList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query tasks */
        get: operations["listTasks"];
        put?: never;
        /**
         * Create a task (idempotent on `id`)
         * @description May include checklist items and reminders, created in the same transaction.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        /**
         * @description `status` accepts only `open` and `dropped` here; use /complete for `done`.
         *     Changing due fields, `rrule` or `status` recomputes reminders.
         */
        patch: operations["patchTask"];
        trace?: never;
    };
    "/tasks/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 409 after the restore window or if the parent list is deleted. */
        post: operations["restoreTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a task or the current occurrence of a recurring task
         * @description Idempotent on `completion_id`: a repeat answers `applied: true` with the existing
         *     completion (SPEC D-24). If `occurrence_due_date` does not match the
         *     task's current `due_date`, nothing is applied (`applied: false`). See SPEC D-10.
         */
        post: operations["completeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip the current occurrence of a recurring task
         * @description Same semantics as /complete. 409 if the task is not recurring.
         */
        post: operations["skipTaskOccurrence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/uncomplete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo a completion or skip
         * @description Restores the state saved in the completion record. Only the latest record of
         *     the task can be undone (409 otherwise). Unknown `completion_id` is a no-op.
         */
        post: operations["uncompleteTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/completions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Completion history, newest first */
        get: operations["listTaskCompletions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Completed occurrences across tasks, newest first
         * @description Feeds the "Completed" section of a list or view. Returns only records of
         *     kind `completed`, each with a summary of its task; records whose task is
         *     deleted are omitted. The client passes the bounds of the current calendar
         *     day in the user's zone. See SPEC section 8, "Completed section".
         */
        get: operations["listCompletions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a one-off `snooze` reminder (idempotent on `reminder_id`) */
        post: operations["snoozeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/checklist-items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a checklist item (idempotent on `id`) */
        post: operations["createChecklistItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checklist-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteChecklistItem"];
        options?: never;
        head?: never;
        patch: operations["patchChecklistItem"];
        trace?: never;
    };
    "/tasks/{id}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a reminder (idempotent on `id`)
         * @description 422 for a `relative` reminder on a task without due date. 409 above 5 reminders.
         */
        post: operations["createReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteReminder"];
        options?: never;
        head?: never;
        patch: operations["patchReminder"];
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTags"];
        put?: never;
        /**
         * Create a tag (idempotent on `id`)
         * @description 409 if another tag of the caller has the same name (case-insensitive).
         */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Soft-deletes the tag and removes it from the `tag_ids` of the caller's tasks. */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        patch: operations["patchTag"];
        trace?: never;
    };
    "/sync/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Incremental changes since a cursor
         * @description Without `cursor`, returns the full live state. With `cursor`, returns every
         *     resource changed since then, including tombstones. Tasks come without the
         *     embedded `checklist_items` and `reminders`; those arrive in their own arrays.
         *     410 when the cursor is older than tombstone retention: discard local state
         *     and start again without cursor.
         */
        get: operations["getChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/vapid-public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public key the browser needs to subscribe to Web Push */
        get: operations["getVapidPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices registered for notifications */
        get: operations["listPushSubscriptions"];
        put?: never;
        /** Register a device (idempotent on `id` and on `endpoint`) */
        post: operations["createPushSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePushSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test notification to this device */
        post: operations["testPushSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            /**
             * @description Stable machine-readable error code (SPEC D-28). New values are added as
             *     phases need them; existing values never change meaning.
             *     - `malformed_request` (400): the body is not valid JSON, is missing, or a
             *       parameter cannot be parsed.
             *     - `unauthenticated` (401): no valid session.
             *     - `forbidden` (403): a cross-origin state-changing request.
             *     - `not_found` (404): the resource does not exist or belongs to someone else.
             *     - `conflict` (409): the request contradicts the resource's state, e.g. renaming the
             *       inbox, a duplicate tag name, an id owned by someone else (SPEC D-23), or a
             *       restore after the 30-day window.
             *     - `cursor_expired` (410): the sync cursor is older than tombstone retention.
             *     - `payload_too_large` (413): the body exceeds 1 MiB (SPEC D-29).
             *     - `unsupported_media_type` (415): the body has the wrong Content-Type.
             *     - `validation_failed` (422): the request violates the schema or a rule;
             *       `errors` lists the fields.
             *     - `rate_limited` (429): too many requests for the session (SPEC D-29).
             *     - `internal` (500): an unexpected server error.
             *     - `not_implemented` (501): the operation, or a field of the request, arrives in a
             *       later phase (SPEC D-34).
             * @enum {string}
             */
            code: "malformed_request" | "unauthenticated" | "forbidden" | "not_found" | "conflict" | "cursor_expired" | "payload_too_large" | "unsupported_media_type" | "validation_failed" | "rate_limited" | "internal" | "not_implemented";
            /** @description Per-field validation errors. */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /**
             * @description JSON Pointer (RFC 6901) to the offending member of the body, e.g.
             *     `/timezone`, or the name of the offending parameter.
             */
            field: string;
            message: string;
        };
        SyncMeta: {
            /** @description Incremented on every write to the resource. */
            readonly version: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            readonly deleted_at?: string | null;
        };
        /** @description Fractional index generated by the client; ordered lexicographically, ties broken by id. */
        Position: string;
        Color: string | null;
        /** @example 09:00 */
        LocalTime: string;
        /**
         * @description IANA time zone name.
         * @example Europe/Madrid
         */
        TimeZone: string;
        User: {
            /** Format: uuid */
            id: string;
            email?: string | null;
            display_name?: string | null;
            timezone: components["schemas"]["TimeZone"];
            all_day_reminder_time: components["schemas"]["LocalTime"];
            /** Format: uuid */
            inbox_list_id: string;
        };
        UserPatch: {
            timezone?: components["schemas"]["TimeZone"];
            all_day_reminder_time?: components["schemas"]["LocalTime"];
        };
        /** @enum {string} */
        ListRole: "owner" | "editor" | "viewer";
        List: components["schemas"]["SyncMeta"] & {
            /** Format: uuid */
            id: string;
            name: string;
            color?: components["schemas"]["Color"];
            position: components["schemas"]["Position"];
            readonly is_inbox: boolean;
            /** @description Caller's role. Always `owner` in V1. */
            readonly role: components["schemas"]["ListRole"];
        };
        ListCreate: {
            /** Format: uuid */
            id: string;
            name: string;
            color?: components["schemas"]["Color"];
            position: components["schemas"]["Position"];
        };
        ListPatch: {
            name?: string;
            color?: components["schemas"]["Color"];
            position?: components["schemas"]["Position"];
        };
        /** @enum {string} */
        TaskStatus: "open" | "done" | "dropped";
        /** @enum {string} */
        RepeatFrom: "due" | "completion";
        /**
         * @description RFC 5545 RRULE restricted to the subset in SPEC section 5. Requires `due_date`.
         * @example FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE
         */
        RRule: string | null;
        Task: components["schemas"]["SyncMeta"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            list_id: string;
            title: string;
            description: string;
            status: components["schemas"]["TaskStatus"];
            /** @description 0 none, 1 low, 2 medium, 3 high. */
            priority: number;
            position: components["schemas"]["Position"];
            /** Format: date */
            due_date?: string | null;
            /** @description Requires `due_date`. */
            due_time?: components["schemas"]["LocalTime"] | null;
            /** @description Requires `due_time`. Null means floating time in the user's current zone. */
            due_tz?: components["schemas"]["TimeZone"] | null;
            rrule?: components["schemas"]["RRule"];
            repeat_from: components["schemas"]["RepeatFrom"];
            readonly recurrence_done_count: number;
            /** Format: date-time */
            readonly completed_at?: string | null;
            tag_ids: string[];
            /** @description Live items ordered by position. Omitted in /sync/changes. */
            readonly checklist_items?: components["schemas"]["ChecklistItem"][];
            /** @description Live reminders. Omitted in /sync/changes. */
            readonly reminders?: components["schemas"]["Reminder"][];
        };
        TaskCreate: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            list_id: string;
            title: string;
            /** @default  */
            description: string;
            /** @default 0 */
            priority: number;
            position: components["schemas"]["Position"];
            /** Format: date */
            due_date?: string | null;
            due_time?: components["schemas"]["LocalTime"] | null;
            due_tz?: components["schemas"]["TimeZone"] | null;
            rrule?: components["schemas"]["RRule"];
            /** @default due */
            repeat_from: components["schemas"]["RepeatFrom"];
            tag_ids?: string[];
            checklist_items?: components["schemas"]["ChecklistItemCreate"][];
            reminders?: components["schemas"]["ReminderCreate"][];
        };
        TaskPatch: {
            /** Format: uuid */
            list_id?: string;
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "open" | "dropped";
            priority?: number;
            position?: components["schemas"]["Position"];
            /** Format: date */
            due_date?: string | null;
            due_time?: components["schemas"]["LocalTime"] | null;
            due_tz?: components["schemas"]["TimeZone"] | null;
            rrule?: components["schemas"]["RRule"];
            repeat_from?: components["schemas"]["RepeatFrom"];
            tag_ids?: string[];
        };
        TaskPage: {
            items: components["schemas"]["Task"][];
            next_cursor?: string | null;
        };
        ChecklistItem: components["schemas"]["SyncMeta"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            readonly task_id: string;
            title: string;
            is_done: boolean;
            position: components["schemas"]["Position"];
        };
        ChecklistItemCreate: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @default false */
            is_done: boolean;
            position: components["schemas"]["Position"];
        };
        ChecklistItemPatch: {
            title?: string;
            is_done?: boolean;
            position?: components["schemas"]["Position"];
        };
        /** @enum {string} */
        ReminderKind: "relative" | "absolute" | "snooze";
        Reminder: components["schemas"]["SyncMeta"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            readonly task_id: string;
            kind: components["schemas"]["ReminderKind"];
            /** @description Only for `relative`. Minutes before the due instant. */
            offset_minutes?: number | null;
            /**
             * Format: date-time
             * @description Only for `absolute` and `snooze`.
             */
            at?: string | null;
            /**
             * Format: date-time
             * @description Computed by the server. Null when nothing is pending.
             */
            readonly next_fire_at?: string | null;
        };
        /** @description Exactly one of `offset_minutes` (relative) or `at` (absolute) must be set. */
        ReminderCreate: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "relative" | "absolute";
            offset_minutes?: number | null;
            /** Format: date-time */
            at?: string | null;
        };
        /** @description The kind cannot change. Send the field matching the reminder's kind. */
        ReminderPatch: {
            offset_minutes?: number;
            /** Format: date-time */
            at?: string;
        };
        Tag: components["schemas"]["SyncMeta"] & {
            /** Format: uuid */
            id: string;
            name: string;
            color?: components["schemas"]["Color"];
        };
        TagCreate: {
            /** Format: uuid */
            id: string;
            name: string;
            color?: components["schemas"]["Color"];
        };
        TagPatch: {
            name?: string;
            color?: components["schemas"]["Color"];
        };
        CompleteRequest: {
            /**
             * Format: uuid
             * @description Generated by the client; makes the call idempotent.
             */
            completion_id: string;
            /**
             * Format: date
             * @description The `due_date` the client saw. Required when the task has a due date.
             */
            occurrence_due_date?: string | null;
            /**
             * Format: date-time
             * @description When the user acted. Defaults to now; future values are clamped to now.
             */
            completed_at?: string;
        };
        Completion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            task_id: string;
            /** @enum {string} */
            kind: "completed" | "skipped";
            /** Format: date */
            occurrence_due_date?: string | null;
            /** Format: date-time */
            completed_at: string;
        };
        TaskSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            list_id: string;
            title: string;
            priority: number;
            /** @description Set when the task is recurring. */
            rrule?: string | null;
        };
        CompletionEntry: components["schemas"]["Completion"] & {
            task: components["schemas"]["TaskSummary"];
            /** @description True when this is the latest record of its task, so /uncomplete accepts it. */
            can_undo: boolean;
        };
        CompletionResult: {
            /**
             * @description False when the call was a no-op: a stale occurrence, or an unknown id on
             *     /uncomplete. A repeated `completion_id` on /complete or /skip answers true
             *     with the existing completion (SPEC D-24).
             */
            applied: boolean;
            task: components["schemas"]["Task"];
            completion?: components["schemas"]["Completion"] | null;
        };
        ChangesPage: {
            lists: components["schemas"]["List"][];
            tasks: components["schemas"]["Task"][];
            checklist_items: components["schemas"]["ChecklistItem"][];
            reminders: components["schemas"]["Reminder"][];
            tags: components["schemas"]["Tag"][];
            /** @description Pass it in the next call, also when `has_more` is false. */
            next_cursor: string;
            has_more: boolean;
        };
        /**
         * @description V1 supports only `webpush`. Future values, e.g. `fcm`, `unifiedpush`, `email`.
         * @enum {string}
         */
        PushChannel: "webpush";
        PushSubscription: {
            /** Format: uuid */
            id: string;
            channel: components["schemas"]["PushChannel"];
            label?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_success_at?: string | null;
            /** Format: date-time */
            disabled_at?: string | null;
        };
        PushSubscriptionCreate: {
            /** Format: uuid */
            id: string;
            channel: components["schemas"]["PushChannel"];
            /** Format: uri */
            endpoint: string;
            keys: {
                p256dh: string;
                auth: string;
            };
            label?: string | null;
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        /** @description Opaque cursor returned by a previous call. */
        Cursor: string;
        Limit: number;
        /** @description When true, returns only soft-deleted resources still restorable (trash). */
        Deleted: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    patchMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listLists: {
        parameters: {
            query?: {
                /** @description When true, returns only soft-deleted resources still restorable (trash). */
                deleted?: components["parameters"]["Deleted"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["List"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListCreate"];
            };
        };
        responses: {
            /** @description Already existed; returned unchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    patchList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ListPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                list_id?: string;
                /** @description Defaults to `open`. */
                status?: components["schemas"]["TaskStatus"];
                /** @description Inclusive lower bound on `due_date`. */
                due_from?: string;
                /** @description Inclusive upper bound on `due_date`. */
                due_to?: string;
                tag_id?: string;
                /** @description Case- and accent-insensitive search on title and description. */
                q?: string;
                sort?: "position" | "due";
                /** @description When true, returns only soft-deleted resources still restorable (trash). */
                deleted?: components["parameters"]["Deleted"];
                /** @description Opaque cursor returned by a previous call. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Already existed; returned unchanged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    patchTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["TaskPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    restoreTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Current state after the (possibly no-op) operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    skipTaskOccurrence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRequest"];
            };
        };
        responses: {
            /** @description Current state after the (possibly no-op) operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    uncompleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    completion_id: string;
                };
            };
        };
        responses: {
            /** @description Current state after the (possibly no-op) operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResult"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTaskCompletions: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned by a previous call. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Completion"][];
                        next_cursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCompletions: {
        parameters: {
            query: {
                /** @description Inclusive lower bound on `completed_at`. */
                completed_from: string;
                /** @description Exclusive upper bound on `completed_at`. */
                completed_to: string;
                list_id?: string;
                tag_id?: string;
                /** @description Inclusive lower bound on `occurrence_due_date`. */
                due_from?: string;
                /** @description Inclusive upper bound on `occurrence_due_date`. */
                due_to?: string;
                /** @description Opaque cursor returned by a previous call. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CompletionEntry"][];
                        next_cursor?: string | null;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    snoozeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    reminder_id: string;
                    /** Format: date-time */
                    until: string;
                };
            };
        };
        responses: {
            /** @description Already existed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createChecklistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChecklistItemCreate"];
            };
        };
        responses: {
            /** @description Already existed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteChecklistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    patchChecklistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ChecklistItemPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChecklistItem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderCreate"];
            };
        };
        responses: {
            /** @description Already existed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    patchReminder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ReminderPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Tag"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Already existed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    patchTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["TagPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getChanges: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned by a previous call. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesPage"];
                };
            };
            /** @description Cursor expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getVapidPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Base64url-encoded P-256 public key. */
                        public_key: string;
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listPushSubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PushSubscription"][];
                    };
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createPushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscriptionCreate"];
            };
        };
        responses: {
            /** @description Already existed; keys refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscription"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushSubscription"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deletePushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    testPushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
}
