// Resource ids are generated by the client (D-03), as UUID version 7: a
// 48-bit Unix time in milliseconds followed by random bits, so ids created
// later sort later. RFC 9562, section 5.7.
import type { Clock } from "./clock";

export function uuidv7(clock: Clock): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);

  // Bytes 0-5: the time, big-endian. JavaScript bit operators work on 32
  // bits, so the 48-bit value is split with division.
  const ms = clock.now().getTime();
  const high = Math.floor(ms / 2 ** 32); // top 16 bits
  const low = ms % 2 ** 32; // bottom 32 bits
  bytes[0] = (high >>> 8) & 0xff;
  bytes[1] = high & 0xff;
  bytes[2] = (low >>> 24) & 0xff;
  bytes[3] = (low >>> 16) & 0xff;
  bytes[4] = (low >>> 8) & 0xff;
  bytes[5] = low & 0xff;

  // Version 7 in the top nibble of byte 6, variant 0b10 in the top bits of
  // byte 8. The "?? 0" only satisfies the type checker: the array has 16
  // bytes.
  bytes[6] = 0x70 | ((bytes[6] ?? 0) & 0x0f);
  bytes[8] = 0x80 | ((bytes[8] ?? 0) & 0x3f);

  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}
