-- Phase 1: users, their lists (only the inbox is created in this phase),
-- list membership, sessions and pending OIDC logins. SPEC section 4.
--
-- Timestamps have no DEFAULT: the application writes them from its injected
-- clock (D-17), so tests control them.

-- +goose Up
CREATE TABLE users (
    -- Generated by the server (SPEC section 4); uuidv7() is built into
    -- PostgreSQL 18.
    id                    uuid        PRIMARY KEY DEFAULT uuidv7(),
    oidc_issuer           text        NOT NULL,
    oidc_subject          text        NOT NULL,
    email                 text,
    display_name          text,
    timezone              text        NOT NULL DEFAULT 'Europe/Madrid',
    all_day_reminder_time time        NOT NULL DEFAULT '09:00',
    created_at            timestamptz NOT NULL,
    updated_at            timestamptz NOT NULL,
    -- D-14: a user is identified by (issuer, subject), never by email.
    CONSTRAINT users_oidc_identity UNIQUE (oidc_issuer, oidc_subject)
);

CREATE TABLE lists (
    -- Generated by the client (D-03); the server generates the inbox's.
    id         uuid        PRIMARY KEY,
    owner_id   uuid        NOT NULL REFERENCES users (id),
    name       text        NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
    color      text        CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    position   text        NOT NULL CHECK (char_length(position) BETWEEN 1 AND 100),
    is_inbox   boolean     NOT NULL DEFAULT false,
    -- Syncable resource (D-07): version counts writes, seq is the global
    -- change counter at the last write.
    version    integer     NOT NULL CHECK (version >= 1),
    seq        bigint      NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    deleted_at timestamptz,
    -- The inbox cannot be deleted (SPEC section 4).
    CONSTRAINT lists_inbox_not_deleted CHECK (NOT is_inbox OR deleted_at IS NULL)
);

-- Exactly one inbox per user. Sign-up creates it while holding the lock on
-- the user's row, so concurrent first logins cannot both create one; this
-- index is the database-level guarantee.
CREATE UNIQUE INDEX lists_one_inbox_per_owner ON lists (owner_id) WHERE is_inbox;

-- /sync/changes reads rows by seq. Every write takes a new seq from the
-- single counter, so values never repeat.
CREATE UNIQUE INDEX lists_seq ON lists (seq);

CREATE TABLE list_members (
    list_id uuid NOT NULL REFERENCES lists (id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users (id),
    role    text NOT NULL CHECK (role IN ('owner', 'editor', 'viewer')),
    PRIMARY KEY (list_id, user_id)
);

-- Every authorization query starts from the user (CLAUDE.md).
CREATE INDEX list_members_user ON list_members (user_id);

CREATE TABLE sessions (
    -- SHA-256 of the session identifier; the clear value lives only in the
    -- browser's cookie (SPEC section 7).
    id_hash      bytea       PRIMARY KEY CHECK (octet_length(id_hash) = 32),
    user_id      uuid        NOT NULL REFERENCES users (id),
    created_at   timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    -- The earlier of the idle limit (last_seen_at + SESSION_IDLE_TIMEOUT)
    -- and the absolute limit (created_at + SESSION_MAX_AGE).
    expires_at   timestamptz NOT NULL
);

-- Revoking a user deletes their sessions (SPEC section 7).
CREATE INDEX sessions_user ON sessions (user_id);

-- A login in progress: what /auth/callback needs to finish it. Bound to the
-- browser that started it by the brinketask_auth cookie, so a callback URL
-- cannot be replayed in another browser (login CSRF). Single use.
CREATE TABLE auth_requests (
    -- SHA-256 of the brinketask_auth cookie value.
    browser_hash  bytea       PRIMARY KEY CHECK (octet_length(browser_hash) = 32),
    state         text        NOT NULL,
    nonce         text        NOT NULL,
    -- PKCE verifier (RFC 7636). Useless without the authorization code.
    code_verifier text        NOT NULL,
    created_at    timestamptz NOT NULL,
    expires_at    timestamptz NOT NULL
);

CREATE INDEX auth_requests_expires ON auth_requests (expires_at);
