// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_requests.sql

package dbgen

import (
	"context"
	"time"
)

const consumeAuthRequest = `-- name: ConsumeAuthRequest :one
DELETE FROM auth_requests WHERE browser_hash = $1 RETURNING browser_hash, state, nonce, code_verifier, created_at, expires_at
`

// Takes the login in progress of a browser and removes it in the same
// statement, so each one can finish at most once.
func (q *Queries) ConsumeAuthRequest(ctx context.Context, browserHash []byte) (AuthRequest, error) {
	row := q.db.QueryRow(ctx, consumeAuthRequest, browserHash)
	var i AuthRequest
	err := row.Scan(
		&i.BrowserHash,
		&i.State,
		&i.Nonce,
		&i.CodeVerifier,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredAuthRequests = `-- name: DeleteExpiredAuthRequests :exec
DELETE FROM auth_requests WHERE expires_at <= $1
`

// Logins abandoned halfway; removed whenever a new one starts.
func (q *Queries) DeleteExpiredAuthRequests(ctx context.Context, now time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthRequests, now)
	return err
}

const insertAuthRequest = `-- name: InsertAuthRequest :exec
INSERT INTO auth_requests (browser_hash, state, nonce, code_verifier, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuthRequestParams struct {
	BrowserHash  []byte
	State        string
	Nonce        string
	CodeVerifier string
	Now          time.Time
	ExpiresAt    time.Time
}

func (q *Queries) InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) error {
	_, err := q.db.Exec(ctx, insertAuthRequest,
		arg.BrowserHash,
		arg.State,
		arg.Nonce,
		arg.CodeVerifier,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}
