// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklist.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checklistItemExists = `-- name: ChecklistItemExists :one
SELECT EXISTS (SELECT 1 FROM checklist_items WHERE id = $1)
`

func (q *Queries) ChecklistItemExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checklistItemExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getChecklistItemForUser = `-- name: GetChecklistItemForUser :one
SELECT c.id, c.task_id, c.title, c.is_done, c.position, c.version, c.seq, c.created_at, c.updated_at, c.deleted_at, (t.deleted_at IS NOT NULL)::boolean AS task_deleted
FROM checklist_items c
JOIN tasks t ON t.id = c.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE c.id = $2
`

type GetChecklistItemForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetChecklistItemForUserRow struct {
	ChecklistItem ChecklistItem
	TaskDeleted   bool
}

// An item of a task in a list the user is a member of, with whether its
// task is deleted.
func (q *Queries) GetChecklistItemForUser(ctx context.Context, arg GetChecklistItemForUserParams) (GetChecklistItemForUserRow, error) {
	row := q.db.QueryRow(ctx, getChecklistItemForUser, arg.UserID, arg.ID)
	var i GetChecklistItemForUserRow
	err := row.Scan(
		&i.ChecklistItem.ID,
		&i.ChecklistItem.TaskID,
		&i.ChecklistItem.Title,
		&i.ChecklistItem.IsDone,
		&i.ChecklistItem.Position,
		&i.ChecklistItem.Version,
		&i.ChecklistItem.Seq,
		&i.ChecklistItem.CreatedAt,
		&i.ChecklistItem.UpdatedAt,
		&i.ChecklistItem.DeletedAt,
		&i.TaskDeleted,
	)
	return i, err
}

const insertChecklistItem = `-- name: InsertChecklistItem :exec
INSERT INTO checklist_items (id, task_id, title, is_done, position, version, seq, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 1, $6, $7, $7)
`

type InsertChecklistItemParams struct {
	ID       uuid.UUID
	TaskID   uuid.UUID
	Title    string
	IsDone   bool
	Position string
	Seq      int64
	Now      time.Time
}

func (q *Queries) InsertChecklistItem(ctx context.Context, arg InsertChecklistItemParams) error {
	_, err := q.db.Exec(ctx, insertChecklistItem,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.IsDone,
		arg.Position,
		arg.Seq,
		arg.Now,
	)
	return err
}

const lockChecklistItemForUser = `-- name: LockChecklistItemForUser :one
SELECT c.id, c.task_id, c.title, c.is_done, c.position, c.version, c.seq, c.created_at, c.updated_at, c.deleted_at, (t.deleted_at IS NOT NULL)::boolean AS task_deleted
FROM checklist_items c
JOIN tasks t ON t.id = c.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE c.id = $2
FOR UPDATE OF c
`

type LockChecklistItemForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type LockChecklistItemForUserRow struct {
	ChecklistItem ChecklistItem
	TaskDeleted   bool
}

func (q *Queries) LockChecklistItemForUser(ctx context.Context, arg LockChecklistItemForUserParams) (LockChecklistItemForUserRow, error) {
	row := q.db.QueryRow(ctx, lockChecklistItemForUser, arg.UserID, arg.ID)
	var i LockChecklistItemForUserRow
	err := row.Scan(
		&i.ChecklistItem.ID,
		&i.ChecklistItem.TaskID,
		&i.ChecklistItem.Title,
		&i.ChecklistItem.IsDone,
		&i.ChecklistItem.Position,
		&i.ChecklistItem.Version,
		&i.ChecklistItem.Seq,
		&i.ChecklistItem.CreatedAt,
		&i.ChecklistItem.UpdatedAt,
		&i.ChecklistItem.DeletedAt,
		&i.TaskDeleted,
	)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :exec
UPDATE checklist_items
SET title = $1, is_done = $2, position = $3, version = $4, seq = $5,
    updated_at = $6, deleted_at = $7
WHERE id = $8
`

type UpdateChecklistItemParams struct {
	Title     string
	IsDone    bool
	Position  string
	Version   int32
	Seq       int64
	UpdatedAt time.Time
	DeletedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) error {
	_, err := q.db.Exec(ctx, updateChecklistItem,
		arg.Title,
		arg.IsDone,
		arg.Position,
		arg.Version,
		arg.Seq,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}
