// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: completions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCompletion = `-- name: GetCompletion :one
SELECT id, task_id, kind, occurrence_due_date, completed_at, prev_due_date, prev_due_time, prev_recurrence_done_count, prev_status, task_seq, undone_at FROM task_completions WHERE id = $1
`

func (q *Queries) GetCompletion(ctx context.Context, id uuid.UUID) (TaskCompletion, error) {
	row := q.db.QueryRow(ctx, getCompletion, id)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.OccurrenceDueDate,
		&i.CompletedAt,
		&i.PrevDueDate,
		&i.PrevDueTime,
		&i.PrevRecurrenceDoneCount,
		&i.PrevStatus,
		&i.TaskSeq,
		&i.UndoneAt,
	)
	return i, err
}

const insertCompletion = `-- name: InsertCompletion :exec
INSERT INTO task_completions (
    id, task_id, kind, occurrence_due_date, completed_at, prev_due_date, prev_due_time,
    prev_recurrence_done_count, prev_status, task_seq
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10
)
`

type InsertCompletionParams struct {
	ID                      uuid.UUID
	TaskID                  uuid.UUID
	Kind                    string
	OccurrenceDueDate       *time.Time
	CompletedAt             time.Time
	PrevDueDate             *time.Time
	PrevDueTime             pgtype.Time
	PrevRecurrenceDoneCount int32
	PrevStatus              string
	TaskSeq                 int64
}

func (q *Queries) InsertCompletion(ctx context.Context, arg InsertCompletionParams) error {
	_, err := q.db.Exec(ctx, insertCompletion,
		arg.ID,
		arg.TaskID,
		arg.Kind,
		arg.OccurrenceDueDate,
		arg.CompletedAt,
		arg.PrevDueDate,
		arg.PrevDueTime,
		arg.PrevRecurrenceDoneCount,
		arg.PrevStatus,
		arg.TaskSeq,
	)
	return err
}

const latestCompletionID = `-- name: LatestCompletionID :one
SELECT id FROM task_completions
WHERE task_id = $1 AND undone_at IS NULL
ORDER BY task_seq DESC
LIMIT 1
`

// The record uncomplete may undo: the newest one not undone (D-39).
func (q *Queries) LatestCompletionID(ctx context.Context, taskID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, latestCompletionID, taskID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCompletions = `-- name: ListCompletions :many
SELECT c.id, c.task_id, c.kind, c.occurrence_due_date, c.completed_at, c.prev_due_date, c.prev_due_time, c.prev_recurrence_done_count, c.prev_status, c.task_seq, c.undone_at, t.list_id, t.title, t.priority, t.rrule,
       c.task_seq = (SELECT max(c2.task_seq) FROM task_completions c2
                     WHERE c2.task_id = c.task_id AND c2.undone_at IS NULL) AS can_undo
FROM task_completions c
JOIN tasks t ON t.id = c.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE c.kind = 'completed' AND c.undone_at IS NULL AND t.deleted_at IS NULL
  AND c.completed_at >= $2 AND c.completed_at < $3
  AND ($4::uuid IS NULL OR t.list_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.tag_ids @> ARRAY[$5::uuid])
  AND ($6::date IS NULL OR c.occurrence_due_date >= $6::date)
  AND ($7::date IS NULL OR c.occurrence_due_date <= $7::date)
  AND (NOT $8::boolean
       OR (c.completed_at, c.id) < ($9::timestamptz, $10::uuid))
ORDER BY c.completed_at DESC, c.id DESC
LIMIT $11
`

type ListCompletionsParams struct {
	UserID           uuid.UUID
	CompletedFrom    time.Time
	CompletedTo      time.Time
	ListID           *uuid.UUID
	TagID            *uuid.UUID
	DueFrom          *time.Time
	DueTo            *time.Time
	HasAfter         bool
	AfterCompletedAt time.Time
	AfterID          uuid.UUID
	Lim              int32
}

type ListCompletionsRow struct {
	TaskCompletion TaskCompletion
	ListID         uuid.UUID
	Title          string
	Priority       int16
	Rrule          *string
	CanUndo        bool
}

// The Completed section (SPEC section 8): completed, not undone records of
// the user's live tasks within [completed_from, completed_to), newest
// first. can_undo marks the latest live record of its task.
func (q *Queries) ListCompletions(ctx context.Context, arg ListCompletionsParams) ([]ListCompletionsRow, error) {
	rows, err := q.db.Query(ctx, listCompletions,
		arg.UserID,
		arg.CompletedFrom,
		arg.CompletedTo,
		arg.ListID,
		arg.TagID,
		arg.DueFrom,
		arg.DueTo,
		arg.HasAfter,
		arg.AfterCompletedAt,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletionsRow
	for rows.Next() {
		var i ListCompletionsRow
		if err := rows.Scan(
			&i.TaskCompletion.ID,
			&i.TaskCompletion.TaskID,
			&i.TaskCompletion.Kind,
			&i.TaskCompletion.OccurrenceDueDate,
			&i.TaskCompletion.CompletedAt,
			&i.TaskCompletion.PrevDueDate,
			&i.TaskCompletion.PrevDueTime,
			&i.TaskCompletion.PrevRecurrenceDoneCount,
			&i.TaskCompletion.PrevStatus,
			&i.TaskCompletion.TaskSeq,
			&i.TaskCompletion.UndoneAt,
			&i.ListID,
			&i.Title,
			&i.Priority,
			&i.Rrule,
			&i.CanUndo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCompletions = `-- name: ListTaskCompletions :many
SELECT id, task_id, kind, occurrence_due_date, completed_at, prev_due_date, prev_due_time, prev_recurrence_done_count, prev_status, task_seq, undone_at FROM task_completions
WHERE task_id = $1 AND undone_at IS NULL
  AND ($2::bigint IS NULL OR task_seq < $2::bigint)
ORDER BY task_seq DESC
LIMIT $3
`

type ListTaskCompletionsParams struct {
	TaskID    uuid.UUID
	BeforeSeq *int64
	Lim       int32
}

// A task's history, newest first, without undone records.
func (q *Queries) ListTaskCompletions(ctx context.Context, arg ListTaskCompletionsParams) ([]TaskCompletion, error) {
	rows, err := q.db.Query(ctx, listTaskCompletions, arg.TaskID, arg.BeforeSeq, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCompletion
	for rows.Next() {
		var i TaskCompletion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.OccurrenceDueDate,
			&i.CompletedAt,
			&i.PrevDueDate,
			&i.PrevDueTime,
			&i.PrevRecurrenceDoneCount,
			&i.PrevStatus,
			&i.TaskSeq,
			&i.UndoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCompletionUndone = `-- name: MarkCompletionUndone :exec
UPDATE task_completions SET undone_at = $1 WHERE id = $2
`

type MarkCompletionUndoneParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkCompletionUndone(ctx context.Context, arg MarkCompletionUndoneParams) error {
	_, err := q.db.Exec(ctx, markCompletionUndone, arg.Now, arg.ID)
	return err
}
