// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertList = `-- name: InsertList :exec
INSERT INTO lists (id, owner_id, name, color, position, is_inbox, version, seq, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7, $8, $8)
`

type InsertListParams struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	Name     string
	Color    *string
	Position string
	IsInbox  bool
	Seq      int64
	Now      time.Time
}

// A new list at version 1. The caller takes seq from NextSeq in the same
// transaction (D-07) and adds the owner's list_members row.
func (q *Queries) InsertList(ctx context.Context, arg InsertListParams) error {
	_, err := q.db.Exec(ctx, insertList,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.IsInbox,
		arg.Seq,
		arg.Now,
	)
	return err
}

const insertListMember = `-- name: InsertListMember :exec
INSERT INTO list_members (list_id, user_id, role) VALUES ($1, $2, $3)
`

type InsertListMemberParams struct {
	ListID uuid.UUID
	UserID uuid.UUID
	Role   string
}

func (q *Queries) InsertListMember(ctx context.Context, arg InsertListMemberParams) error {
	_, err := q.db.Exec(ctx, insertListMember, arg.ListID, arg.UserID, arg.Role)
	return err
}
