// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthRequest struct {
	BrowserHash  []byte
	State        string
	Nonce        string
	CodeVerifier string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type List struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Color     *string
	Position  string
	IsInbox   bool
	Version   int32
	Seq       int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type ListMember struct {
	ListID uuid.UUID
	UserID uuid.UUID
	Role   string
}

type Session struct {
	IDHash     []byte
	UserID     uuid.UUID
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type SyncState struct {
	ID  bool
	Seq int64
}

type User struct {
	ID                 uuid.UUID
	OidcIssuer         string
	OidcSubject        string
	Email              *string
	DisplayName        *string
	Timezone           string
	AllDayReminderTime pgtype.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
