// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purge.sql

package dbgen

import (
	"context"
	"time"
)

const purgeChecklistItems = `-- name: PurgeChecklistItems :many
DELETE FROM checklist_items c USING tasks t
WHERE t.id = c.task_id AND (c.deleted_at < $1 OR t.deleted_at < $1)
RETURNING c.seq
`

func (q *Queries) PurgeChecklistItems(ctx context.Context, cutoff *time.Time) ([]int64, error) {
	rows, err := q.db.Query(ctx, purgeChecklistItems, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeCompletions = `-- name: PurgeCompletions :execrows
DELETE FROM task_completions c USING tasks t
WHERE t.id = c.task_id AND t.deleted_at < $1
`

// Completion records go only with their task; a live task keeps them all
// (SPEC section 1).
func (q *Queries) PurgeCompletions(ctx context.Context, cutoff *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeCompletions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeDeliveries = `-- name: PurgeDeliveries :execrows
DELETE FROM notification_deliveries d
WHERE d.created_at < $1
   OR d.reminder_id IN (
        SELECT r.id FROM reminders r JOIN tasks t ON t.id = r.task_id
        WHERE r.deleted_at < $1 OR t.deleted_at < $1)
`

// Deliveries of purged reminders, and any delivery older than the cutoff.
func (q *Queries) PurgeDeliveries(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeliveries, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredSessions = `-- name: PurgeExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1
`

func (q *Queries) PurgeExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeListMembers = `-- name: PurgeListMembers :execrows
DELETE FROM list_members m USING lists l
WHERE l.id = m.list_id AND l.deleted_at < $1
  AND NOT EXISTS (SELECT 1 FROM tasks t WHERE t.list_id = l.id)
`

func (q *Queries) PurgeListMembers(ctx context.Context, cutoff *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeListMembers, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeLists = `-- name: PurgeLists :many
DELETE FROM lists l
WHERE l.deleted_at < $1 AND NOT EXISTS (SELECT 1 FROM tasks t WHERE t.list_id = l.id)
RETURNING l.seq
`

// A list goes once its tasks are gone; deleting a list deletes its tasks
// at the same moment (D-20), so they are purged together.
func (q *Queries) PurgeLists(ctx context.Context, cutoff *time.Time) ([]int64, error) {
	rows, err := q.db.Query(ctx, purgeLists, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeReminders = `-- name: PurgeReminders :many
DELETE FROM reminders r USING tasks t
WHERE t.id = r.task_id AND (r.deleted_at < $1 OR t.deleted_at < $1)
RETURNING r.seq
`

func (q *Queries) PurgeReminders(ctx context.Context, cutoff *time.Time) ([]int64, error) {
	rows, err := q.db.Query(ctx, purgeReminders, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeTags = `-- name: PurgeTags :many
DELETE FROM tags WHERE deleted_at < $1 RETURNING seq
`

func (q *Queries) PurgeTags(ctx context.Context, cutoff *time.Time) ([]int64, error) {
	rows, err := q.db.Query(ctx, purgeTags, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeTasks = `-- name: PurgeTasks :many
DELETE FROM tasks WHERE deleted_at < $1 RETURNING seq
`

func (q *Queries) PurgeTasks(ctx context.Context, cutoff *time.Time) ([]int64, error) {
	rows, err := q.db.Query(ctx, purgeTasks, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raisePurgedUpTo = `-- name: RaisePurgedUpTo :exec
UPDATE sync_state SET purged_up_to_seq = greatest(purged_up_to_seq, $1::bigint)
`

// D-21: a sync cursor below this seq may have missed a purged tombstone.
func (q *Queries) RaisePurgedUpTo(ctx context.Context, seq int64) error {
	_, err := q.db.Exec(ctx, raisePurgedUpTo, seq)
	return err
}

const tryPurgeLock = `-- name: TryPurgeLock :one

SELECT pg_try_advisory_xact_lock(7240618253::bigint)
`

// The purge (SPEC section 8, D-71): resources deleted more than 90 days
// ago go for good, with what depends on them, children before parents
// because of the foreign keys. A row is purgeable when it, or the task it
// belongs to, was deleted before @cutoff.
// One purge at a time across replicas. A transaction-level advisory lock
// is released by the commit; the key is an arbitrary constant of this
// application.
func (q *Queries) TryPurgeLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryPurgeLock)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
