// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteSubscriptionForUser = `-- name: DeleteSubscriptionForUser :execrows
DELETE FROM push_subscriptions WHERE id = $1 AND user_id = $2
`

type DeleteSubscriptionForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSubscriptionForUser(ctx context.Context, arg DeleteSubscriptionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscriptionForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableSubscription = `-- name: DisableSubscription :exec
UPDATE push_subscriptions SET disabled_at = $1 WHERE id = $2 AND disabled_at IS NULL
`

type DisableSubscriptionParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) DisableSubscription(ctx context.Context, arg DisableSubscriptionParams) error {
	_, err := q.db.Exec(ctx, disableSubscription, arg.Now, arg.ID)
	return err
}

const getSubscriptionForUser = `-- name: GetSubscriptionForUser :one
SELECT id, user_id, channel, endpoint, p256dh, auth, label, created_at, last_success_at, disabled_at FROM push_subscriptions WHERE id = $1 AND user_id = $2
`

type GetSubscriptionForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSubscriptionForUser(ctx context.Context, arg GetSubscriptionForUserParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForUser, arg.ID, arg.UserID)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.Label,
		&i.CreatedAt,
		&i.LastSuccessAt,
		&i.DisabledAt,
	)
	return i, err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO push_subscriptions (id, user_id, channel, endpoint, p256dh, auth, label, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSubscriptionParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Channel  string
	Endpoint string
	P256dh   string
	Auth     string
	Label    *string
	Now      time.Time
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertSubscription,
		arg.ID,
		arg.UserID,
		arg.Channel,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.Label,
		arg.Now,
	)
	return err
}

const listSubscriptionsForUser = `-- name: ListSubscriptionsForUser :many

SELECT id, user_id, channel, endpoint, p256dh, auth, label, created_at, last_success_at, disabled_at FROM push_subscriptions WHERE user_id = $1 ORDER BY created_at, id
`

// Web Push subscriptions (devices). Not syncable; deleted for real (D-32).
func (q *Queries) ListSubscriptionsForUser(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.Label,
			&i.CreatedAt,
			&i.LastSuccessAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSubscriptionByEndpoint = `-- name: LockSubscriptionByEndpoint :one
SELECT id, user_id, channel, endpoint, p256dh, auth, label, created_at, last_success_at, disabled_at FROM push_subscriptions WHERE endpoint = $1 FOR UPDATE
`

func (q *Queries) LockSubscriptionByEndpoint(ctx context.Context, endpoint string) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, lockSubscriptionByEndpoint, endpoint)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.Label,
		&i.CreatedAt,
		&i.LastSuccessAt,
		&i.DisabledAt,
	)
	return i, err
}

const lockSubscriptionByID = `-- name: LockSubscriptionByID :one
SELECT id, user_id, channel, endpoint, p256dh, auth, label, created_at, last_success_at, disabled_at FROM push_subscriptions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSubscriptionByID(ctx context.Context, id uuid.UUID) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, lockSubscriptionByID, id)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.Label,
		&i.CreatedAt,
		&i.LastSuccessAt,
		&i.DisabledAt,
	)
	return i, err
}

const refreshSubscription = `-- name: RefreshSubscription :exec
UPDATE push_subscriptions
SET user_id = $1, p256dh = $2, auth = $3, label = $4, disabled_at = NULL
WHERE id = $5
`

type RefreshSubscriptionParams struct {
	UserID uuid.UUID
	P256dh string
	Auth   string
	Label  *string
	ID     uuid.UUID
}

// A device registering again: its keys may have changed, it may now belong
// to another user (D-32), and it works again if it had been disabled.
func (q *Queries) RefreshSubscription(ctx context.Context, arg RefreshSubscriptionParams) error {
	_, err := q.db.Exec(ctx, refreshSubscription,
		arg.UserID,
		arg.P256dh,
		arg.Auth,
		arg.Label,
		arg.ID,
	)
	return err
}

const subscriptionSucceeded = `-- name: SubscriptionSucceeded :exec
UPDATE push_subscriptions SET last_success_at = $1 WHERE id = $2
`

type SubscriptionSucceededParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) SubscriptionSucceeded(ctx context.Context, arg SubscriptionSucceededParams) error {
	_, err := q.db.Exec(ctx, subscriptionSucceeded, arg.Now, arg.ID)
	return err
}
