// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLiveRemindersOfTask = `-- name: CountLiveRemindersOfTask :one
SELECT count(*)::integer FROM reminders
WHERE task_id = $1 AND deleted_at IS NULL AND kind <> 'snooze'
`

// The reminders that count towards the limit of 5 (snooze ones do not).
func (q *Queries) CountLiveRemindersOfTask(ctx context.Context, taskID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveRemindersOfTask, taskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getReminderForUser = `-- name: GetReminderForUser :one
SELECT r.id, r.task_id, r.kind, r.offset_minutes, r.at, r.next_fire_at, r.last_fired_at, r.version, r.seq, r.created_at, r.updated_at, r.deleted_at, (t.deleted_at IS NOT NULL)::boolean AS task_deleted
FROM reminders r
JOIN tasks t ON t.id = r.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE r.id = $2
`

type GetReminderForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetReminderForUserRow struct {
	Reminder    Reminder
	TaskDeleted bool
}

// A reminder of a task in a list the user is a member of, with whether its
// task is deleted.
func (q *Queries) GetReminderForUser(ctx context.Context, arg GetReminderForUserParams) (GetReminderForUserRow, error) {
	row := q.db.QueryRow(ctx, getReminderForUser, arg.UserID, arg.ID)
	var i GetReminderForUserRow
	err := row.Scan(
		&i.Reminder.ID,
		&i.Reminder.TaskID,
		&i.Reminder.Kind,
		&i.Reminder.OffsetMinutes,
		&i.Reminder.At,
		&i.Reminder.NextFireAt,
		&i.Reminder.LastFiredAt,
		&i.Reminder.Version,
		&i.Reminder.Seq,
		&i.Reminder.CreatedAt,
		&i.Reminder.UpdatedAt,
		&i.Reminder.DeletedAt,
		&i.TaskDeleted,
	)
	return i, err
}

const insertReminder = `-- name: InsertReminder :exec
INSERT INTO reminders (id, task_id, kind, offset_minutes, at, next_fire_at, version, seq, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, $7, $8, $8)
`

type InsertReminderParams struct {
	ID            uuid.UUID
	TaskID        uuid.UUID
	Kind          string
	OffsetMinutes *int32
	At            *time.Time
	NextFireAt    *time.Time
	Seq           int64
	Now           time.Time
}

func (q *Queries) InsertReminder(ctx context.Context, arg InsertReminderParams) error {
	_, err := q.db.Exec(ctx, insertReminder,
		arg.ID,
		arg.TaskID,
		arg.Kind,
		arg.OffsetMinutes,
		arg.At,
		arg.NextFireAt,
		arg.Seq,
		arg.Now,
	)
	return err
}

const liveRemindersForTasks = `-- name: LiveRemindersForTasks :many
SELECT id, task_id, kind, offset_minutes, at, next_fire_at, last_fired_at, version, seq, created_at, updated_at, deleted_at FROM reminders
WHERE task_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY task_id, created_at, id
`

func (q *Queries) LiveRemindersForTasks(ctx context.Context, taskIds []uuid.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, liveRemindersForTasks, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.OffsetMinutes,
			&i.At,
			&i.NextFireAt,
			&i.LastFiredAt,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveRemindersOfTask = `-- name: LockLiveRemindersOfTask :many
SELECT id, task_id, kind, offset_minutes, at, next_fire_at, last_fired_at, version, seq, created_at, updated_at, deleted_at FROM reminders
WHERE task_id = $1 AND deleted_at IS NULL
ORDER BY id
FOR UPDATE
`

// A task's live reminders, locked, to recompute them after the task
// changed. The caller holds the task's lock already.
func (q *Queries) LockLiveRemindersOfTask(ctx context.Context, taskID uuid.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, lockLiveRemindersOfTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.OffsetMinutes,
			&i.At,
			&i.NextFireAt,
			&i.LastFiredAt,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveRemindersOfUser = `-- name: LockLiveRemindersOfUser :many
SELECT r.id, r.task_id, r.kind, r.offset_minutes, r.at, r.next_fire_at, r.last_fired_at, r.version, r.seq, r.created_at, r.updated_at, r.deleted_at, t.id, t.list_id, t.title, t.description, t.status, t.priority, t.position, t.due_date, t.due_time, t.due_tz, t.rrule, t.repeat_from, t.recurrence_done_count, t.completed_at, t.tag_ids, t.deleted_with_list_id, t.version, t.seq, t.created_at, t.updated_at, t.deleted_at, t.recurrence_start
FROM reminders r
JOIN tasks t ON t.id = r.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE r.deleted_at IS NULL
ORDER BY r.id
FOR UPDATE OF r
`

type LockLiveRemindersOfUserRow struct {
	Reminder Reminder
	Task     Task
}

// Every live reminder of the user's tasks, with its task, locked: changing
// the profile zone or default time recomputes them (SPEC section 6).
func (q *Queries) LockLiveRemindersOfUser(ctx context.Context, userID uuid.UUID) ([]LockLiveRemindersOfUserRow, error) {
	rows, err := q.db.Query(ctx, lockLiveRemindersOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockLiveRemindersOfUserRow
	for rows.Next() {
		var i LockLiveRemindersOfUserRow
		if err := rows.Scan(
			&i.Reminder.ID,
			&i.Reminder.TaskID,
			&i.Reminder.Kind,
			&i.Reminder.OffsetMinutes,
			&i.Reminder.At,
			&i.Reminder.NextFireAt,
			&i.Reminder.LastFiredAt,
			&i.Reminder.Version,
			&i.Reminder.Seq,
			&i.Reminder.CreatedAt,
			&i.Reminder.UpdatedAt,
			&i.Reminder.DeletedAt,
			&i.Task.ID,
			&i.Task.ListID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.Status,
			&i.Task.Priority,
			&i.Task.Position,
			&i.Task.DueDate,
			&i.Task.DueTime,
			&i.Task.DueTz,
			&i.Task.Rrule,
			&i.Task.RepeatFrom,
			&i.Task.RecurrenceDoneCount,
			&i.Task.CompletedAt,
			&i.Task.TagIds,
			&i.Task.DeletedWithListID,
			&i.Task.Version,
			&i.Task.Seq,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.DeletedAt,
			&i.Task.RecurrenceStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReminderForUser = `-- name: LockReminderForUser :one
SELECT r.id, r.task_id, r.kind, r.offset_minutes, r.at, r.next_fire_at, r.last_fired_at, r.version, r.seq, r.created_at, r.updated_at, r.deleted_at, (t.deleted_at IS NOT NULL)::boolean AS task_deleted
FROM reminders r
JOIN tasks t ON t.id = r.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE r.id = $2
FOR UPDATE OF r
`

type LockReminderForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type LockReminderForUserRow struct {
	Reminder    Reminder
	TaskDeleted bool
}

func (q *Queries) LockReminderForUser(ctx context.Context, arg LockReminderForUserParams) (LockReminderForUserRow, error) {
	row := q.db.QueryRow(ctx, lockReminderForUser, arg.UserID, arg.ID)
	var i LockReminderForUserRow
	err := row.Scan(
		&i.Reminder.ID,
		&i.Reminder.TaskID,
		&i.Reminder.Kind,
		&i.Reminder.OffsetMinutes,
		&i.Reminder.At,
		&i.Reminder.NextFireAt,
		&i.Reminder.LastFiredAt,
		&i.Reminder.Version,
		&i.Reminder.Seq,
		&i.Reminder.CreatedAt,
		&i.Reminder.UpdatedAt,
		&i.Reminder.DeletedAt,
		&i.TaskDeleted,
	)
	return i, err
}

const reminderExists = `-- name: ReminderExists :one
SELECT EXISTS (SELECT 1 FROM reminders WHERE id = $1)
`

func (q *Queries) ReminderExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, reminderExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateReminder = `-- name: UpdateReminder :exec
UPDATE reminders
SET offset_minutes = $1, at = $2, next_fire_at = $3,
    last_fired_at = $4, version = $5, seq = $6, updated_at = $7,
    deleted_at = $8
WHERE id = $9
`

type UpdateReminderParams struct {
	OffsetMinutes *int32
	At            *time.Time
	NextFireAt    *time.Time
	LastFiredAt   *time.Time
	Version       int32
	Seq           int64
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	ID            uuid.UUID
}

// Writes every mutable column; the caller read the row under lock.
func (q *Queries) UpdateReminder(ctx context.Context, arg UpdateReminderParams) error {
	_, err := q.db.Exec(ctx, updateReminder,
		arg.OffsetMinutes,
		arg.At,
		arg.NextFireAt,
		arg.LastFiredAt,
		arg.Version,
		arg.Seq,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}
