// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeSubscriptionsForTask = `-- name: ActiveSubscriptionsForTask :many
SELECT s.id FROM push_subscriptions s
JOIN list_members m ON m.user_id = s.user_id
JOIN tasks t ON t.list_id = m.list_id
WHERE t.id = $1 AND s.disabled_at IS NULL
ORDER BY s.id
`

// The devices of every member of the task's list.
func (q *Queries) ActiveSubscriptionsForTask(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activeSubscriptionsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueDelivery = `-- name: ClaimDueDelivery :one
SELECT d.id, d.reminder_id, d.fire_at, d.attempts,
       s.id AS subscription_id, s.endpoint, s.p256dh, s.auth,
       t.id AS task_id, t.title, t.due_date, t.due_time, t.due_tz,
       l.name AS list_name, l.is_inbox, u.timezone
FROM notification_deliveries d
JOIN push_subscriptions s ON s.id = d.subscription_id
JOIN reminders r ON r.id = d.reminder_id
JOIN tasks t ON t.id = r.task_id
JOIN lists l ON l.id = t.list_id
JOIN users u ON u.id = s.user_id
WHERE d.status = 'pending' AND d.next_attempt_at <= $1
ORDER BY d.next_attempt_at
LIMIT 1
FOR UPDATE OF d SKIP LOCKED
`

type ClaimDueDeliveryRow struct {
	ID             uuid.UUID
	ReminderID     uuid.UUID
	FireAt         time.Time
	Attempts       int32
	SubscriptionID uuid.UUID
	Endpoint       string
	P256dh         string
	Auth           string
	TaskID         uuid.UUID
	Title          string
	DueDate        *time.Time
	DueTime        pgtype.Time
	DueTz          *string
	ListName       string
	IsInbox        bool
	Timezone       string
}

// One pending delivery that is due, with what its message needs.
func (q *Queries) ClaimDueDelivery(ctx context.Context, now *time.Time) (ClaimDueDeliveryRow, error) {
	row := q.db.QueryRow(ctx, claimDueDelivery, now)
	var i ClaimDueDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.ReminderID,
		&i.FireAt,
		&i.Attempts,
		&i.SubscriptionID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.TaskID,
		&i.Title,
		&i.DueDate,
		&i.DueTime,
		&i.DueTz,
		&i.ListName,
		&i.IsInbox,
		&i.Timezone,
	)
	return i, err
}

const claimDueReminders = `-- name: ClaimDueReminders :many

SELECT id, task_id, kind, offset_minutes, at, next_fire_at, last_fired_at, version, seq, created_at, updated_at, deleted_at FROM reminders
WHERE next_fire_at <= $1 AND deleted_at IS NULL
ORDER BY next_fire_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimDueRemindersParams struct {
	Now *time.Time
	Lim int32
}

// The reminder scheduler (SPEC section 6). Every claim uses FOR UPDATE SKIP
// LOCKED: two schedulers (two replicas, or two loops in a test) never take
// the same row, and neither waits for the other (D-16).
func (q *Queries) ClaimDueReminders(ctx context.Context, arg ClaimDueRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, claimDueReminders, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.OffsetMinutes,
			&i.At,
			&i.NextFireAt,
			&i.LastFiredAt,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO notification_deliveries (reminder_id, fire_at, subscription_id, status, next_attempt_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT ON CONSTRAINT notification_deliveries_once DO NOTHING
`

type InsertDeliveryParams struct {
	ReminderID     uuid.UUID
	FireAt         time.Time
	SubscriptionID uuid.UUID
	Status         string
	NextAttemptAt  *time.Time
	Now            time.Time
}

// ON CONFLICT: a firing already has its delivery for that device.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery,
		arg.ReminderID,
		arg.FireAt,
		arg.SubscriptionID,
		arg.Status,
		arg.NextAttemptAt,
		arg.Now,
	)
	return err
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE notification_deliveries
SET status = 'failed', attempts = attempts + 1, next_attempt_at = NULL, error = $1
WHERE id = $2
`

type MarkDeliveryFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed, arg.Error, arg.ID)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE notification_deliveries
SET attempts = attempts + 1, next_attempt_at = $1, error = $2
WHERE id = $3
`

type MarkDeliveryRetryParams struct {
	NextAttemptAt *time.Time
	Error         *string
	ID            uuid.UUID
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, markDeliveryRetry, arg.NextAttemptAt, arg.Error, arg.ID)
	return err
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE notification_deliveries
SET status = 'sent', attempts = attempts + 1, sent_at = $1, next_attempt_at = NULL, error = NULL
WHERE id = $2
`

type MarkDeliverySentParams struct {
	Now *time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) error {
	_, err := q.db.Exec(ctx, markDeliverySent, arg.Now, arg.ID)
	return err
}
