// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND expires_at <= $2
`

type DeleteExpiredSessionsParams struct {
	UserID uuid.UUID
	Now    time.Time
}

// Expired sessions are useless; they are removed when their user logs in
// again or when someone presents them.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, arg.UserID, arg.Now)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, idHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, idHash)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id_hash, user_id, created_at, last_seen_at, expires_at FROM sessions WHERE id_hash = $1
`

func (q *Queries) GetSession(ctx context.Context, idHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, idHash)
	var i Session
	err := row.Scan(
		&i.IDHash,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id_hash, user_id, created_at, last_seen_at, expires_at)
VALUES ($1, $2, $3, $3, $4)
`

type InsertSessionParams struct {
	IDHash    []byte
	UserID    uuid.UUID
	Now       time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.IDHash,
		arg.UserID,
		arg.Now,
		arg.ExpiresAt,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1, expires_at = $2 WHERE id_hash = $3
`

type TouchSessionParams struct {
	Now       time.Time
	ExpiresAt time.Time
	IDHash    []byte
}

// Records use of a session and slides its expiry (SPEC section 7).
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Now, arg.ExpiresAt, arg.IDHash)
	return err
}
