// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package dbgen

import (
	"context"
)

const nextSeq = `-- name: NextSeq :one
UPDATE sync_state SET seq = seq + 1 RETURNING seq
`

// Takes the next value of the global change counter (D-07). The UPDATE
// locks the single sync_state row until the transaction ends, so concurrent
// writers take numbers one at a time and a reader never sees seq N+1
// committed before seq N.
func (q *Queries) NextSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}
