// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getSyncState = `-- name: GetSyncState :one
SELECT seq, purged_up_to_seq FROM sync_state
`

type GetSyncStateRow struct {
	Seq           int64
	PurgedUpToSeq int64
}

func (q *Queries) GetSyncState(ctx context.Context) (GetSyncStateRow, error) {
	row := q.db.QueryRow(ctx, getSyncState)
	var i GetSyncStateRow
	err := row.Scan(&i.Seq, &i.PurgedUpToSeq)
	return i, err
}

const nextSeq = `-- name: NextSeq :one
UPDATE sync_state SET seq = seq + 1 RETURNING seq
`

// Takes the next value of the global change counter (D-07). The UPDATE
// locks the single sync_state row until the transaction ends, so concurrent
// writers take numbers one at a time and a reader never sees seq N+1
// committed before seq N.
func (q *Queries) NextSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const reserveSeqs = `-- name: ReserveSeqs :one
UPDATE sync_state SET seq = seq + $1::bigint RETURNING seq
`

// Takes @n consecutive values of the counter at once and returns the last
// one; the caller uses last-n+1 .. last. Same lock as NextSeq. A write that
// touches many rows (deleting a list deletes its tasks) gives each row its
// own seq this way with one statement.
func (q *Queries) ReserveSeqs(ctx context.Context, n int64) (int64, error) {
	row := q.db.QueryRow(ctx, reserveSeqs, n)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const syncChecklistItems = `-- name: SyncChecklistItems :many
SELECT c.id, c.task_id, c.title, c.is_done, c.position, c.version, c.seq, c.created_at, c.updated_at, c.deleted_at FROM checklist_items c
JOIN tasks t ON t.id = c.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE c.seq > $2 AND c.seq <= $3
  AND (NOT $4::boolean OR (c.deleted_at IS NULL AND t.deleted_at IS NULL))
ORDER BY c.seq
`

type SyncChecklistItemsParams struct {
	UserID   uuid.UUID
	After    int64
	Upper    int64
	LiveOnly bool
}

func (q *Queries) SyncChecklistItems(ctx context.Context, arg SyncChecklistItemsParams) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, syncChecklistItems,
		arg.UserID,
		arg.After,
		arg.Upper,
		arg.LiveOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.IsDone,
			&i.Position,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncLists = `-- name: SyncLists :many
SELECT l.id, l.owner_id, l.name, l.color, l.position, l.is_inbox, l.version, l.seq, l.created_at, l.updated_at, l.deleted_at, m.role FROM lists l
JOIN list_members m ON m.list_id = l.id AND m.user_id = $1
WHERE l.seq > $2 AND l.seq <= $3 AND (NOT $4::boolean OR l.deleted_at IS NULL)
ORDER BY l.seq
`

type SyncListsParams struct {
	UserID   uuid.UUID
	After    int64
	Upper    int64
	LiveOnly bool
}

type SyncListsRow struct {
	List List
	Role string
}

func (q *Queries) SyncLists(ctx context.Context, arg SyncListsParams) ([]SyncListsRow, error) {
	rows, err := q.db.Query(ctx, syncLists,
		arg.UserID,
		arg.After,
		arg.Upper,
		arg.LiveOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncListsRow
	for rows.Next() {
		var i SyncListsRow
		if err := rows.Scan(
			&i.List.ID,
			&i.List.OwnerID,
			&i.List.Name,
			&i.List.Color,
			&i.List.Position,
			&i.List.IsInbox,
			&i.List.Version,
			&i.List.Seq,
			&i.List.CreatedAt,
			&i.List.UpdatedAt,
			&i.List.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncPageSeqs = `-- name: SyncPageSeqs :many

SELECT s.seq FROM (
    SELECT l.seq FROM lists l
    JOIN list_members m ON m.list_id = l.id AND m.user_id = $1
    WHERE l.seq > $2 AND (NOT $3::boolean OR l.deleted_at IS NULL)
    UNION ALL
    SELECT t.seq FROM tasks t
    JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
    WHERE t.seq > $2 AND (NOT $3::boolean OR t.deleted_at IS NULL)
    UNION ALL
    SELECT c.seq FROM checklist_items c
    JOIN tasks t ON t.id = c.task_id
    JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
    WHERE c.seq > $2
      AND (NOT $3::boolean OR (c.deleted_at IS NULL AND t.deleted_at IS NULL))
    UNION ALL
    SELECT r.seq FROM reminders r
    JOIN tasks t ON t.id = r.task_id
    JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
    WHERE r.seq > $2
      AND (NOT $3::boolean OR (r.deleted_at IS NULL AND t.deleted_at IS NULL))
    UNION ALL
    SELECT g.seq FROM tags g
    WHERE g.owner_id = $1 AND g.seq > $2
      AND (NOT $3::boolean OR g.deleted_at IS NULL)
) s
ORDER BY s.seq
LIMIT $4
`

type SyncPageSeqsParams struct {
	UserID   uuid.UUID
	After    int64
	LiveOnly bool
	Lim      int32
}

// The /sync/changes queries (SPEC section 8). A page holds the rows with
// after < seq <= upper; SyncPageSeqs finds upper. With live_only (no
// cursor: the full live state) tombstones are left out, and so are the
// items of deleted tasks.
func (q *Queries) SyncPageSeqs(ctx context.Context, arg SyncPageSeqsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, syncPageSeqs,
		arg.UserID,
		arg.After,
		arg.LiveOnly,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var seq int64
		if err := rows.Scan(&seq); err != nil {
			return nil, err
		}
		items = append(items, seq)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncReminders = `-- name: SyncReminders :many
SELECT r.id, r.task_id, r.kind, r.offset_minutes, r.at, r.next_fire_at, r.last_fired_at, r.version, r.seq, r.created_at, r.updated_at, r.deleted_at FROM reminders r
JOIN tasks t ON t.id = r.task_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE r.seq > $2 AND r.seq <= $3
  AND (NOT $4::boolean OR (r.deleted_at IS NULL AND t.deleted_at IS NULL))
ORDER BY r.seq
`

type SyncRemindersParams struct {
	UserID   uuid.UUID
	After    int64
	Upper    int64
	LiveOnly bool
}

func (q *Queries) SyncReminders(ctx context.Context, arg SyncRemindersParams) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, syncReminders,
		arg.UserID,
		arg.After,
		arg.Upper,
		arg.LiveOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.OffsetMinutes,
			&i.At,
			&i.NextFireAt,
			&i.LastFiredAt,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncTags = `-- name: SyncTags :many
SELECT id, owner_id, name, color, version, seq, created_at, updated_at, deleted_at FROM tags
WHERE owner_id = $1 AND seq > $2 AND seq <= $3
  AND (NOT $4::boolean OR deleted_at IS NULL)
ORDER BY seq
`

type SyncTagsParams struct {
	UserID   uuid.UUID
	After    int64
	Upper    int64
	LiveOnly bool
}

func (q *Queries) SyncTags(ctx context.Context, arg SyncTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, syncTags,
		arg.UserID,
		arg.After,
		arg.Upper,
		arg.LiveOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncTasks = `-- name: SyncTasks :many
SELECT t.id, t.list_id, t.title, t.description, t.status, t.priority, t.position, t.due_date, t.due_time, t.due_tz, t.rrule, t.repeat_from, t.recurrence_done_count, t.completed_at, t.tag_ids, t.deleted_with_list_id, t.version, t.seq, t.created_at, t.updated_at, t.deleted_at, t.recurrence_start FROM tasks t
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE t.seq > $2 AND t.seq <= $3 AND (NOT $4::boolean OR t.deleted_at IS NULL)
ORDER BY t.seq
`

type SyncTasksParams struct {
	UserID   uuid.UUID
	After    int64
	Upper    int64
	LiveOnly bool
}

func (q *Queries) SyncTasks(ctx context.Context, arg SyncTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, syncTasks,
		arg.UserID,
		arg.After,
		arg.Upper,
		arg.LiveOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Position,
			&i.DueDate,
			&i.DueTime,
			&i.DueTz,
			&i.Rrule,
			&i.RepeatFrom,
			&i.RecurrenceDoneCount,
			&i.CompletedAt,
			&i.TagIds,
			&i.DeletedWithListID,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RecurrenceStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
