// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getTagForUser = `-- name: GetTagForUser :one

SELECT id, owner_id, name, color, version, seq, created_at, updated_at, deleted_at FROM tags WHERE id = $1 AND owner_id = $2
`

type GetTagForUserParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

// Tags belong to a user (owner_id), not to a list.
func (q *Queries) GetTagForUser(ctx context.Context, arg GetTagForUserParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagForUser, arg.ID, arg.OwnerID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.Version,
		&i.Seq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO tags (id, owner_id, name, color, version, seq, created_at, updated_at)
VALUES ($1, $2, $3, $4, 1, $5, $6, $6)
`

type InsertTagParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
	Color   *string
	Seq     int64
	Now     time.Time
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.Exec(ctx, insertTag,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Color,
		arg.Seq,
		arg.Now,
	)
	return err
}

const listLiveTags = `-- name: ListLiveTags :many
SELECT id, owner_id, name, color, version, seq, created_at, updated_at, deleted_at FROM tags WHERE owner_id = $1 AND deleted_at IS NULL ORDER BY lower(name), id
`

func (q *Queries) ListLiveTags(ctx context.Context, ownerID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listLiveTags, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveTagNameTaken = `-- name: LiveTagNameTaken :one
SELECT EXISTS (
    SELECT 1 FROM tags
    WHERE owner_id = $1 AND deleted_at IS NULL AND lower(name) = lower($2) AND id <> $3
)
`

type LiveTagNameTakenParams struct {
	OwnerID uuid.UUID
	Name    string
	ID      uuid.UUID
}

// Whether another live tag of the user has this name, ignoring case.
func (q *Queries) LiveTagNameTaken(ctx context.Context, arg LiveTagNameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, liveTagNameTaken, arg.OwnerID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockLiveTags = `-- name: LockLiveTags :many
SELECT id FROM tags
WHERE owner_id = $1 AND deleted_at IS NULL AND id = ANY($2::uuid[])
FOR SHARE
`

type LockLiveTagsParams struct {
	OwnerID uuid.UUID
	Ids     []uuid.UUID
}

// Which of ids are live tags of the user. FOR SHARE keeps them from being
// deleted until the task that references them is written.
func (q *Queries) LockLiveTags(ctx context.Context, arg LockLiveTagsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockLiveTags, arg.OwnerID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTagForUser = `-- name: LockTagForUser :one
SELECT id, owner_id, name, color, version, seq, created_at, updated_at, deleted_at FROM tags WHERE id = $1 AND owner_id = $2 FOR UPDATE
`

type LockTagForUserParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) LockTagForUser(ctx context.Context, arg LockTagForUserParams) (Tag, error) {
	row := q.db.QueryRow(ctx, lockTagForUser, arg.ID, arg.OwnerID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.Version,
		&i.Seq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockTaskIDsWithTag = `-- name: LockTaskIDsWithTag :many
SELECT t.id
FROM tasks t
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE t.tag_ids @> ARRAY[$2::uuid]
ORDER BY t.id
FOR UPDATE OF t
`

type LockTaskIDsWithTagParams struct {
	UserID uuid.UUID
	TagID  uuid.UUID
}

// The user's tasks, live or deleted, that carry the tag.
func (q *Queries) LockTaskIDsWithTag(ctx context.Context, arg LockTaskIDsWithTagParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockTaskIDsWithTag, arg.UserID, arg.TagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromTasks = `-- name: RemoveTagFromTasks :exec
UPDATE tasks t
SET tag_ids = array_remove(t.tag_ids, $1::uuid), version = t.version + 1,
    seq = v.seq, updated_at = $2
FROM (SELECT unnest($3::uuid[]) AS id, unnest($4::bigint[]) AS seq) AS v
WHERE t.id = v.id
`

type RemoveTagFromTasksParams struct {
	TagID uuid.UUID
	Now   time.Time
	Ids   []uuid.UUID
	Seqs  []int64
}

// Two unnest calls in one SELECT list advance together, pairing ids[i]
// with seqs[i].
func (q *Queries) RemoveTagFromTasks(ctx context.Context, arg RemoveTagFromTasksParams) error {
	_, err := q.db.Exec(ctx, removeTagFromTasks,
		arg.TagID,
		arg.Now,
		arg.Ids,
		arg.Seqs,
	)
	return err
}

const tagExists = `-- name: TagExists :one
SELECT EXISTS (SELECT 1 FROM tags WHERE id = $1)
`

func (q *Queries) TagExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tagExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTag = `-- name: UpdateTag :exec
UPDATE tags
SET name = $1, color = $2, version = $3, seq = $4,
    updated_at = $5, deleted_at = $6
WHERE id = $7
`

type UpdateTagParams struct {
	Name      string
	Color     *string
	Version   int32
	Seq       int64
	UpdatedAt time.Time
	DeletedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.Exec(ctx, updateTag,
		arg.Name,
		arg.Color,
		arg.Version,
		arg.Seq,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}
