// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskForUser = `-- name: GetTaskForUser :one
SELECT t.id, t.list_id, t.title, t.description, t.status, t.priority, t.position, t.due_date, t.due_time, t.due_tz, t.rrule, t.repeat_from, t.recurrence_done_count, t.completed_at, t.tag_ids, t.deleted_with_list_id, t.version, t.seq, t.created_at, t.updated_at, t.deleted_at, t.recurrence_start
FROM tasks t
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE t.id = $2
`

type GetTaskForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

// A task in a list the user is a member of, live or deleted.
func (q *Queries) GetTaskForUser(ctx context.Context, arg GetTaskForUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForUser, arg.UserID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Position,
		&i.DueDate,
		&i.DueTime,
		&i.DueTz,
		&i.Rrule,
		&i.RepeatFrom,
		&i.RecurrenceDoneCount,
		&i.CompletedAt,
		&i.TagIds,
		&i.DeletedWithListID,
		&i.Version,
		&i.Seq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecurrenceStart,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (
    id, list_id, title, description, status, priority, position, due_date, due_time, due_tz,
    rrule, recurrence_start, repeat_from, tag_ids, version, seq, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, 'open', $5, $6, $7, $8, $9,
    $10, $11, $12, $13, 1, $14, $15, $15
)
`

type InsertTaskParams struct {
	ID              uuid.UUID
	ListID          uuid.UUID
	Title           string
	Description     string
	Priority        int16
	Position        string
	DueDate         *time.Time
	DueTime         pgtype.Time
	DueTz           *string
	Rrule           *string
	RecurrenceStart *time.Time
	RepeatFrom      string
	TagIds          []uuid.UUID
	Seq             int64
	Now             time.Time
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.Exec(ctx, insertTask,
		arg.ID,
		arg.ListID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Position,
		arg.DueDate,
		arg.DueTime,
		arg.DueTz,
		arg.Rrule,
		arg.RecurrenceStart,
		arg.RepeatFrom,
		arg.TagIds,
		arg.Seq,
		arg.Now,
	)
	return err
}

const listIsLive = `-- name: ListIsLive :one
SELECT (deleted_at IS NULL)::boolean FROM lists WHERE id = $1
`

func (q *Queries) ListIsLive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, listIsLive, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const liveChecklistItemsForTasks = `-- name: LiveChecklistItemsForTasks :many
SELECT id, task_id, title, is_done, position, version, seq, created_at, updated_at, deleted_at FROM checklist_items
WHERE task_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY task_id, position, id
`

func (q *Queries) LiveChecklistItemsForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, liveChecklistItemsForTasks, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.IsDone,
			&i.Position,
			&i.Version,
			&i.Seq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskForUser = `-- name: LockTaskForUser :one
SELECT t.id, t.list_id, t.title, t.description, t.status, t.priority, t.position, t.due_date, t.due_time, t.due_tz, t.rrule, t.repeat_from, t.recurrence_done_count, t.completed_at, t.tag_ids, t.deleted_with_list_id, t.version, t.seq, t.created_at, t.updated_at, t.deleted_at, t.recurrence_start
FROM tasks t
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE t.id = $2
FOR UPDATE OF t
`

type LockTaskForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) LockTaskForUser(ctx context.Context, arg LockTaskForUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, lockTaskForUser, arg.UserID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Position,
		&i.DueDate,
		&i.DueTime,
		&i.DueTz,
		&i.Rrule,
		&i.RepeatFrom,
		&i.RecurrenceDoneCount,
		&i.CompletedAt,
		&i.TagIds,
		&i.DeletedWithListID,
		&i.Version,
		&i.Seq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecurrenceStart,
	)
	return i, err
}

const queryTasksByDue = `-- name: QueryTasksByDue :many
SELECT t.id, t.list_id, t.title, t.description, t.status, t.priority, t.position, t.due_date, t.due_time, t.due_tz, t.rrule, t.repeat_from, t.recurrence_done_count, t.completed_at, t.tag_ids, t.deleted_with_list_id, t.version, t.seq, t.created_at, t.updated_at, t.deleted_at, t.recurrence_start, l.position AS list_position
FROM tasks t
JOIN lists l ON l.id = t.list_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE CASE WHEN $2::boolean
           THEN t.deleted_at > $3::timestamptz
                AND t.deleted_with_list_id IS NULL AND l.deleted_at IS NULL
           ELSE t.deleted_at IS NULL END
  AND ($4::text IS NULL OR t.status = $4::text)
  AND ($5::uuid IS NULL OR t.list_id = $5::uuid)
  AND ($6::uuid IS NULL OR t.tag_ids @> ARRAY[$6::uuid])
  AND ($7::date IS NULL OR t.due_date >= $7::date)
  AND ($8::date IS NULL OR t.due_date <= $8::date)
  AND ($9::text IS NULL
       OR unaccent(lower(t.title)) LIKE unaccent(lower($9::text)) ESCAPE '\'
       OR unaccent(lower(t.description)) LIKE unaccent(lower($9::text)) ESCAPE '\')
  AND (NOT $10::boolean
       OR (coalesce(t.due_date, 'infinity'::date), t.due_time IS NOT NULL,
           coalesce(t.due_time, '00:00'::time), t.position, t.id)
          > (($11::text)::date, $12::boolean, ($13::text)::time,
             $14::text, $15::uuid))
ORDER BY coalesce(t.due_date, 'infinity'::date), t.due_time IS NOT NULL,
         coalesce(t.due_time, '00:00'::time), t.position, t.id
LIMIT $16
`

type QueryTasksByDueParams struct {
	UserID          uuid.UUID
	Trash           bool
	RestorableSince time.Time
	Status          *string
	ListID          *uuid.UUID
	TagID           *uuid.UUID
	DueFrom         *time.Time
	DueTo           *time.Time
	Pattern         *string
	HasAfter        bool
	AfterDueDate    string
	AfterTimed      bool
	AfterDueTime    string
	AfterPosition   string
	AfterID         uuid.UUID
	Lim             int32
}

type QueryTasksByDueRow struct {
	Task         Task
	ListPosition string
}

// GET /tasks with sort=due (D-43): no date last, all-day before timed. The
// sort key replaces NULLs with values that sort the same way, because a
// row comparison with a NULL is never true. The keyset date and time
// arrive as text so the cursor can carry 'infinity'.
func (q *Queries) QueryTasksByDue(ctx context.Context, arg QueryTasksByDueParams) ([]QueryTasksByDueRow, error) {
	rows, err := q.db.Query(ctx, queryTasksByDue,
		arg.UserID,
		arg.Trash,
		arg.RestorableSince,
		arg.Status,
		arg.ListID,
		arg.TagID,
		arg.DueFrom,
		arg.DueTo,
		arg.Pattern,
		arg.HasAfter,
		arg.AfterDueDate,
		arg.AfterTimed,
		arg.AfterDueTime,
		arg.AfterPosition,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryTasksByDueRow
	for rows.Next() {
		var i QueryTasksByDueRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.ListID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.Status,
			&i.Task.Priority,
			&i.Task.Position,
			&i.Task.DueDate,
			&i.Task.DueTime,
			&i.Task.DueTz,
			&i.Task.Rrule,
			&i.Task.RepeatFrom,
			&i.Task.RecurrenceDoneCount,
			&i.Task.CompletedAt,
			&i.Task.TagIds,
			&i.Task.DeletedWithListID,
			&i.Task.Version,
			&i.Task.Seq,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.DeletedAt,
			&i.Task.RecurrenceStart,
			&i.ListPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryTasksByPosition = `-- name: QueryTasksByPosition :many
SELECT t.id, t.list_id, t.title, t.description, t.status, t.priority, t.position, t.due_date, t.due_time, t.due_tz, t.rrule, t.repeat_from, t.recurrence_done_count, t.completed_at, t.tag_ids, t.deleted_with_list_id, t.version, t.seq, t.created_at, t.updated_at, t.deleted_at, t.recurrence_start, l.position AS list_position
FROM tasks t
JOIN lists l ON l.id = t.list_id
JOIN list_members m ON m.list_id = t.list_id AND m.user_id = $1
WHERE CASE WHEN $2::boolean
           THEN t.deleted_at > $3::timestamptz
                AND t.deleted_with_list_id IS NULL AND l.deleted_at IS NULL
           ELSE t.deleted_at IS NULL END
  AND ($4::text IS NULL OR t.status = $4::text)
  AND ($5::uuid IS NULL OR t.list_id = $5::uuid)
  AND ($6::uuid IS NULL OR t.tag_ids @> ARRAY[$6::uuid])
  AND ($7::date IS NULL OR t.due_date >= $7::date)
  AND ($8::date IS NULL OR t.due_date <= $8::date)
  AND ($9::text IS NULL
       OR unaccent(lower(t.title)) LIKE unaccent(lower($9::text)) ESCAPE '\'
       OR unaccent(lower(t.description)) LIKE unaccent(lower($9::text)) ESCAPE '\')
  AND (NOT $10::boolean
       OR (l.position, l.id, t.position, t.id)
          > ($11::text, $12::uuid, $13::text, $14::uuid))
ORDER BY l.position, l.id, t.position, t.id
LIMIT $15
`

type QueryTasksByPositionParams struct {
	UserID            uuid.UUID
	Trash             bool
	RestorableSince   time.Time
	Status            *string
	ListID            *uuid.UUID
	TagID             *uuid.UUID
	DueFrom           *time.Time
	DueTo             *time.Time
	Pattern           *string
	HasAfter          bool
	AfterListPosition string
	AfterListID       uuid.UUID
	AfterPosition     string
	AfterID           uuid.UUID
	Lim               int32
}

type QueryTasksByPositionRow struct {
	Task         Task
	ListPosition string
}

// GET /tasks with sort=position: by the list's position, then the task's
// (D-43). The filters are optional: a NULL argument disables its filter.
// The keyset condition continues after the last row of the previous page.
func (q *Queries) QueryTasksByPosition(ctx context.Context, arg QueryTasksByPositionParams) ([]QueryTasksByPositionRow, error) {
	rows, err := q.db.Query(ctx, queryTasksByPosition,
		arg.UserID,
		arg.Trash,
		arg.RestorableSince,
		arg.Status,
		arg.ListID,
		arg.TagID,
		arg.DueFrom,
		arg.DueTo,
		arg.Pattern,
		arg.HasAfter,
		arg.AfterListPosition,
		arg.AfterListID,
		arg.AfterPosition,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryTasksByPositionRow
	for rows.Next() {
		var i QueryTasksByPositionRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.ListID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.Status,
			&i.Task.Priority,
			&i.Task.Position,
			&i.Task.DueDate,
			&i.Task.DueTime,
			&i.Task.DueTz,
			&i.Task.Rrule,
			&i.Task.RepeatFrom,
			&i.Task.RecurrenceDoneCount,
			&i.Task.CompletedAt,
			&i.Task.TagIds,
			&i.Task.DeletedWithListID,
			&i.Task.Version,
			&i.Task.Seq,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.DeletedAt,
			&i.Task.RecurrenceStart,
			&i.ListPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskExists = `-- name: TaskExists :one
SELECT EXISTS (SELECT 1 FROM tasks WHERE id = $1)
`

func (q *Queries) TaskExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, taskExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET list_id = $1, title = $2, description = $3, status = $4,
    priority = $5, position = $6, due_date = $7, due_time = $8,
    due_tz = $9, rrule = $10, recurrence_start = $11, repeat_from = $12,
    recurrence_done_count = $13, completed_at = $14,
    tag_ids = $15, version = $16, seq = $17, updated_at = $18,
    deleted_at = $19
WHERE id = $20
`

type UpdateTaskParams struct {
	ListID              uuid.UUID
	Title               string
	Description         string
	Status              string
	Priority            int16
	Position            string
	DueDate             *time.Time
	DueTime             pgtype.Time
	DueTz               *string
	Rrule               *string
	RecurrenceStart     *time.Time
	RepeatFrom          string
	RecurrenceDoneCount int32
	CompletedAt         *time.Time
	TagIds              []uuid.UUID
	Version             int32
	Seq                 int64
	UpdatedAt           time.Time
	DeletedAt           *time.Time
	ID                  uuid.UUID
}

// Writes every mutable column; the caller read the row under lock and
// changed what the request asked for.
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ListID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Position,
		arg.DueDate,
		arg.DueTime,
		arg.DueTz,
		arg.Rrule,
		arg.RecurrenceStart,
		arg.RepeatFrom,
		arg.RecurrenceDoneCount,
		arg.CompletedAt,
		arg.TagIds,
		arg.Version,
		arg.Seq,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}
