// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getInboxID = `-- name: GetInboxID :one
SELECT l.id
FROM lists l
JOIN list_members m ON m.list_id = l.id
WHERE m.user_id = $1 AND m.role = 'owner' AND l.is_inbox AND l.owner_id = $1
`

// Membership-filtered like every data access (CLAUDE.md): the inbox the
// user owns.
func (q *Queries) GetInboxID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getInboxID, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id, oidc_issuer, oidc_subject, email, display_name, timezone, all_day_reminder_time, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.AllDayReminderTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE users
SET timezone              = coalesce($1, timezone),
    all_day_reminder_time = coalesce($2, all_day_reminder_time),
    updated_at = CASE
        WHEN coalesce($1, timezone) IS DISTINCT FROM timezone
          OR coalesce($2, all_day_reminder_time) IS DISTINCT FROM all_day_reminder_time
        THEN $3
        ELSE updated_at
    END
WHERE id = $4
RETURNING id, oidc_issuer, oidc_subject, email, display_name, timezone, all_day_reminder_time, created_at, updated_at
`

type UpdateUserSettingsParams struct {
	Timezone           *string
	AllDayReminderTime pgtype.Time
	Now                time.Time
	ID                 uuid.UUID
}

// Merge patch of the profile settings (D-05): a NULL argument leaves its
// column alone. updated_at only moves when a value actually changes.
func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.Timezone,
		arg.AllDayReminderTime,
		arg.Now,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.Timezone,
		&i.AllDayReminderTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (oidc_issuer, oidc_subject, email, display_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (oidc_issuer, oidc_subject) DO UPDATE
SET email        = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    updated_at   = CASE
        WHEN users.email IS DISTINCT FROM EXCLUDED.email
          OR users.display_name IS DISTINCT FROM EXCLUDED.display_name
        THEN EXCLUDED.updated_at
        ELSE users.updated_at
    END
RETURNING id
`

type UpsertUserParams struct {
	OidcIssuer  string
	OidcSubject string
	Email       *string
	DisplayName *string
	Now         time.Time
}

// Signs a user in by OIDC identity (D-14): creates the row on the first
// login and refreshes the informational claims on later ones. Either way
// the row stays locked until the transaction ends, which serializes two
// concurrent logins of the same user. updated_at only moves when a claim
// changed.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.Email,
		arg.DisplayName,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
